using System;
using System.Collections.Generic;
using CheckmateRPG.Core;
using CheckmateRPG.Core.Actions;
using CheckmateRPG.Core.Events.ActionEvents;
using CheckmateRPG.Core.Effects;
using CheckmateRPG.Core.Runtime.Mutations;
using CheckmateRPG.Core.Simulation;
using CheckmateRPG.Units;

namespace CheckmateRPG.Core.Runtime.Processors
{
    /// <summary>
    /// The sole layer permitted to apply mutations to RuntimeState.
    /// Routes each <see cref="IRuntimeMutation"/> to its dedicated sub-processor
    /// and aggregates the resulting events.
    /// </summary>
    public sealed class RuntimeMutationProcessor
    {
        private readonly DamageMutationProcessor _damageProcessor;
        private readonly MovementMutationProcessor _movementProcessor;
        private readonly EffectMutationProcessor _effectProcessor;
        private readonly CooldownMutationProcessor _cooldownProcessor;
        private readonly Func<AbilityActionCompleteMutation, bool> _applyAbilityActionComplete;

        public RuntimeMutationProcessor(
            Func<Guid, UnitBrain> unitLookup,
            SimulationRuntime simulationRuntime,
            Func<EffectRuntimeState, bool> applyEffect,
            Func<string, bool> isPhysicalCcEffect,
            Func<ApplyEffectMutation, ApplyEffectMutation> substituteWithStagger,
            Func<Guid, string, AbilityRuntimeState> abilityStateLookup,
            Func<int> currentTickProvider,
            Func<AbilityActionCompleteMutation, bool> applyAbilityActionComplete)
        {
            if (unitLookup == null)
                throw new ArgumentNullException(nameof(unitLookup));
            if (simulationRuntime == null)
                throw new ArgumentNullException(nameof(simulationRuntime));
            if (applyEffect == null)
                throw new ArgumentNullException(nameof(applyEffect));
            if (isPhysicalCcEffect == null)
                throw new ArgumentNullException(nameof(isPhysicalCcEffect));
            if (substituteWithStagger == null)
                throw new ArgumentNullException(nameof(substituteWithStagger));
            if (abilityStateLookup == null)
                throw new ArgumentNullException(nameof(abilityStateLookup));
            if (currentTickProvider == null)
                throw new ArgumentNullException(nameof(currentTickProvider));
            if (applyAbilityActionComplete == null)
                throw new ArgumentNullException(nameof(applyAbilityActionComplete));

            _damageProcessor = new DamageMutationProcessor(unitLookup, simulationRuntime);
            _movementProcessor = new MovementMutationProcessor(unitLookup, simulationRuntime);
            _effectProcessor = new EffectMutationProcessor(simulationRuntime, applyEffect, isPhysicalCcEffect, substituteWithStagger);
            _cooldownProcessor = new CooldownMutationProcessor(abilityStateLookup, currentTickProvider);
            _applyAbilityActionComplete = applyAbilityActionComplete;
        }

        /// <summary>
        /// Applies all mutations in order and returns the events generated by each processor.
        /// </summary>
        public IReadOnlyList<IGameEvent> Apply(IReadOnlyList<IRuntimeMutation> mutations)
        {
            if (mutations == null || mutations.Count == 0)
                return Array.Empty<IGameEvent>();

            var processingQueue = new MutationQueue();
            for (int i = 0; i < mutations.Count; i++)
            {
                if (mutations[i] != null)
                    processingQueue.Enqueue(mutations[i], ActionSpeedTier.Normal, int.MaxValue);
            }

            var events = new List<IGameEvent>();
            while (processingQueue.Count > 0)
            {
                IRuntimeMutation mutation = processingQueue.Dequeue();
                if (mutation == null)
                    continue;

                MutationApplyResult applyResult = ApplySingle(mutation, out bool handled);
                IReadOnlyList<IGameEvent> mutationEvents = applyResult.Events;
                events.AddRange(mutationEvents);
                if (handled)
                    events.Add(BuildMutationAppliedEvent(mutation));

                IReadOnlyList<IRuntimeMutation> generated = applyResult.GeneratedMutations;
                if (generated == null || generated.Count == 0)
                    continue;

                for (int i = 0; i < generated.Count; i++)
                {
                    if (generated[i] != null)
                        processingQueue.Enqueue(generated[i], ActionSpeedTier.Normal, int.MaxValue);
                }
            }

            return events;
        }

        public IReadOnlyList<IGameEvent> Apply(MutationQueue queue)
        {
            if (queue == null)
                throw new ArgumentNullException(nameof(queue));
            if (queue.Count == 0)
                return Array.Empty<IGameEvent>();

            var events = new List<IGameEvent>();
            while (queue.Count > 0)
            {
                if (queue.Dequeue() is not IRuntimeMutation mutation)
                    continue;

                MutationApplyResult applyResult = ApplySingle(mutation, out bool handled);
                IReadOnlyList<IGameEvent> mutationEvents = applyResult.Events;
                events.AddRange(mutationEvents);
                if (handled)
                    events.Add(BuildMutationAppliedEvent(mutation));

                IReadOnlyList<IRuntimeMutation> generated = applyResult.GeneratedMutations;
                if (generated == null || generated.Count == 0)
                    continue;

                for (int i = 0; i < generated.Count; i++)
                {
                    if (generated[i] != null)
                        queue.Enqueue(generated[i], ActionSpeedTier.Normal, int.MaxValue);
                }
            }

            return events;
        }

        public IReadOnlyList<IGameEvent> Apply(RuntimeTransaction transaction, MutationOrderingService orderingService)
        {
            if (transaction == null)
                throw new ArgumentNullException(nameof(transaction));
            if (orderingService == null)
                throw new ArgumentNullException(nameof(orderingService));
            if (transaction.Count == 0)
            {
                transaction.Commit();
                return Array.Empty<IGameEvent>();
            }

            IReadOnlyList<IRuntimeMutation> ordered = transaction.CreateOrderedSnapshot(orderingService);
            IReadOnlyList<IGameEvent> events = Apply(ordered);
            transaction.Commit();
            return events;
        }

        private MutationApplyResult ApplySingle(IRuntimeMutation mutation, out bool handled)
        {
            handled = true;
            return mutation switch
            {
                DamageMutation damage => new MutationApplyResult(_damageProcessor.Apply(damage), Array.Empty<IRuntimeMutation>()),
                HealMutation heal => new MutationApplyResult(_damageProcessor.Apply(heal), Array.Empty<IRuntimeMutation>()),
                DeathMutation death => new MutationApplyResult(_damageProcessor.Apply(death), Array.Empty<IRuntimeMutation>()),
                MovementMutation movement => ToApplyResult(_movementProcessor.ApplyWithGeneratedMutations(movement)),
                MoveMutation move => ToApplyResult(_movementProcessor.ApplyWithGeneratedMutations(move)),
                ApplyEffectMutation effect => new MutationApplyResult(_effectProcessor.Apply(effect), Array.Empty<IRuntimeMutation>()),
                CooldownMutation cooldown => new MutationApplyResult(_cooldownProcessor.Apply(cooldown), Array.Empty<IRuntimeMutation>()),
                AbilityActionCompleteMutation abilityComplete => new MutationApplyResult(ApplyAbilityStateMutation(abilityComplete), Array.Empty<IRuntimeMutation>()),
                ReservationMutation => new MutationApplyResult(Array.Empty<IGameEvent>(), Array.Empty<IRuntimeMutation>()),
                ResourceMutation => new MutationApplyResult(Array.Empty<IGameEvent>(), Array.Empty<IRuntimeMutation>()),
                _ => MarkUnhandled(out handled)
            };
        }

        private static MutationApplyResult ToApplyResult(MovementProcessResult movementResult)
        {
            return new MutationApplyResult(
                movementResult.Events ?? Array.Empty<IGameEvent>(),
                movementResult.GeneratedMutations ?? Array.Empty<IRuntimeMutation>());
        }

        private static MutationApplyResult MarkUnhandled(out bool handled)
        {
            handled = false;
            return new MutationApplyResult(Array.Empty<IGameEvent>(), Array.Empty<IRuntimeMutation>());
        }

        private IReadOnlyList<IGameEvent> ApplyAbilityStateMutation(AbilityActionCompleteMutation mutation)
        {
            _ = _applyAbilityActionComplete(mutation);
            return Array.Empty<IGameEvent>();
        }

        private static MutationAppliedEvent BuildMutationAppliedEvent(IRuntimeMutation mutation)
        {
            Guid sourceAction = ResolveSourceAction(mutation);
            int tick = ResolveTick(mutation);
            string mutationType = mutation.GetType().Name;
            return new MutationAppliedEvent(
                new MutationAppliedPayload(
                    mutation.MutationId,
                    mutation.TargetId,
                    mutationType,
                    sourceAction,
                    tick),
                mutation.MutationId.ToString("N"),
                mutation.TargetId.ToString("N"));
        }

        private static Guid ResolveSourceAction(IRuntimeMutation mutation)
        {
            if (mutation.Context.SourceAction != Guid.Empty)
                return mutation.Context.SourceAction;

            return mutation switch
            {
                AbilityActionCompleteMutation abilityComplete => abilityComplete.ActionId,
                _ => Guid.Empty
            };
        }

        private static int ResolveTick(IRuntimeMutation mutation)
        {
            if (mutation.Context.Tick > 0)
                return mutation.Context.Tick;

            return mutation switch
            {
                DeathMutation death => death.Tick,
                ReservationMutation reservation => reservation.Tick,
                AbilityActionCompleteMutation abilityComplete => abilityComplete.Tick,
                _ => 0
            };
        }

        private readonly record struct MutationApplyResult(
            IReadOnlyList<IGameEvent> Events,
            IReadOnlyList<IRuntimeMutation> GeneratedMutations);
    }
}
