using System;
using System.Collections.Generic;
using CheckmateRPG.Core;
using CheckmateRPG.Core.Runtime.Mutations;
using CheckmateRPG.Units;

namespace CheckmateRPG.Core.Runtime.Processors
{
    /// <summary>
    /// The sole layer permitted to apply mutations to RuntimeState.
    /// Routes each <see cref="IRuntimeMutation"/> to its dedicated sub-processor
    /// and aggregates the resulting events.
    /// </summary>
    public sealed class RuntimeMutationProcessor
    {
        private readonly DamageMutationProcessor _damageProcessor;
        private readonly MovementMutationProcessor _movementProcessor;

        public RuntimeMutationProcessor(Func<Guid, UnitBrain> unitLookup)
        {
            if (unitLookup == null)
                throw new ArgumentNullException(nameof(unitLookup));

            _damageProcessor = new DamageMutationProcessor(unitLookup);
            _movementProcessor = new MovementMutationProcessor(unitLookup);
        }

        /// <summary>
        /// Applies all mutations in order and returns the events generated by each processor.
        /// </summary>
        public IReadOnlyList<IGameEvent> Apply(IReadOnlyList<IRuntimeMutation> mutations)
        {
            if (mutations == null || mutations.Count == 0)
                return Array.Empty<IGameEvent>();

            var events = new List<IGameEvent>();
            for (int i = 0; i < mutations.Count; i++)
            {
                IReadOnlyList<IGameEvent> mutationEvents = mutations[i] switch
                {
                    DamageMutation dm => _damageProcessor.Apply(dm),
                    MovementMutation mm => _movementProcessor.Apply(mm),
                    _ => Array.Empty<IGameEvent>()
                };
                events.AddRange(mutationEvents);
            }
            return events;
        }
    }
}
