using System;
using System.Collections.Generic;
using CheckmateRPG.Core;
using CheckmateRPG.Core.Effects;
using CheckmateRPG.Core.Runtime.Mutations;
using CheckmateRPG.Core.Simulation;
using CheckmateRPG.Units;

namespace CheckmateRPG.Core.Runtime.Processors
{
    /// <summary>
    /// The sole layer permitted to apply mutations to RuntimeState.
    /// Routes each <see cref="IRuntimeMutation"/> to its dedicated sub-processor
    /// and aggregates the resulting events.
    /// </summary>
    public sealed class RuntimeMutationProcessor
    {
        private readonly DamageMutationProcessor _damageProcessor;
        private readonly MovementMutationProcessor _movementProcessor;
        private readonly EffectMutationProcessor _effectProcessor;

        public RuntimeMutationProcessor(
            Func<Guid, UnitBrain> unitLookup,
            SimulationRuntime simulationRuntime,
            Func<EffectRuntimeState, bool> applyEffect)
        {
            if (unitLookup == null)
                throw new ArgumentNullException(nameof(unitLookup));
            if (simulationRuntime == null)
                throw new ArgumentNullException(nameof(simulationRuntime));
            if (applyEffect == null)
                throw new ArgumentNullException(nameof(applyEffect));

            _damageProcessor = new DamageMutationProcessor(unitLookup, simulationRuntime);
            _movementProcessor = new MovementMutationProcessor(unitLookup, simulationRuntime);
            _effectProcessor = new EffectMutationProcessor(applyEffect);
        }

        /// <summary>
        /// Applies all mutations in order and returns the events generated by each processor.
        /// </summary>
        public IReadOnlyList<IGameEvent> Apply(IReadOnlyList<IRuntimeMutation> mutations)
        {
            if (mutations == null || mutations.Count == 0)
                return Array.Empty<IGameEvent>();

            var events = new List<IGameEvent>();
            for (int i = 0; i < mutations.Count; i++)
            {
                IReadOnlyList<IGameEvent> mutationEvents = mutations[i] switch
                {
                    DamageMutation dm => _damageProcessor.Apply(dm),
                    MovementMutation mm => _movementProcessor.Apply(mm),
                    ApplyEffectMutation em => _effectProcessor.Apply(em),
                    _ => Array.Empty<IGameEvent>()
                };
                events.AddRange(mutationEvents);
            }
            return events;
        }

        public IReadOnlyList<IGameEvent> Apply(RuntimeTransaction transaction, MutationOrderingService orderingService)
        {
            if (transaction == null)
                throw new ArgumentNullException(nameof(transaction));
            if (orderingService == null)
                throw new ArgumentNullException(nameof(orderingService));
            if (transaction.Count == 0)
            {
                transaction.Commit();
                return Array.Empty<IGameEvent>();
            }

            IReadOnlyList<IRuntimeMutation> ordered = transaction.CreateOrderedSnapshot(orderingService);
            IReadOnlyList<IGameEvent> events = Apply(ordered);
            transaction.Commit();
            return events;
        }
    }
}
